CREATE TABLE [dbo].[CLIENTES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[SOBRENOME] [varchar](255) NOT NULL,
	[NACIONALIDADE] [varchar](50) NOT NULL,
	[CEP] [varchar](9) NOT NULL,
	[ESTADO] [varchar](2) NOT NULL,
	[CIDADE] [varchar](50) NOT NULL,
	[LOGRADOURO] [varchar](500) NOT NULL,
	[EMAIL] [varchar](2079) NULL,
	[TELEFONE] [varchar](15) NULL,
	[CPF] [varchar](14) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

