CREATE TABLE [dbo].[BENEFICIARIOS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CPF] [varchar](14) NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[IDCLIENTE] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


